
import "./globals.css";
import Navbar from "../ui/Navbar";
import Sidebar from "../ui/Sidebar";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      
    >
      <body className="bg-white text-black">
          <Navbar />
          <div className="">
            <div className="mx-auto ">
              <div className="flex">
                <Sidebar />
                <main className="flex-1 min-w-0">
                  {children}
                </main>
              </div>
            </div>
          </div>
      </body>
    </html>
  );
}
