import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../ui/Navbar";
import Sidebar from "../ui/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body className="bg-white">
          <Navbar />
          <div className="">
            <div className="mx-auto ">
              <div className="flex">
                <Sidebar />
                <main className="flex-1 min-w-0">
                  {children}
                </main>
              </div>
            </div>
          </div>
      </body>
    </html>
  );
}
